TeCAS.SCA.WebAdmin/Controllers/CustomerController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using TeCAS.SCA.Entities;
using TeCAS.SCA.Services.Operations;
using TeCAS.SCA.WebAdmin.Models;

namespace TeCAS.SCA.WebAdmin.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerOperations _helperCustomer;
        private readonly IMapper _mapper;

        public CustomerController(ICustomerOperations helperCustomer, IMapper mapper)
        {
            _helperCustomer = helperCustomer;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public List<CustomerVM> GetCustomers()
        {
            var customers = _helperCustomer.GetAll();
            var customerVm = _mapper.Map<List<Customer>, List<CustomerVM>>(customers);

            return customerVm;
        }

        public IActionResult Edit(Guid id)
        {
            var tmp = _helperCustomer.RetrieveById(id);

            if(tmp != null)
            {
                var customerVM = _mapper.Map<CustomerVM>(tmp);
                return View("AddCustomer", customerVM);
            }

            return RedirectToAction("Index");
        }

        public IActionResult AddCustomer()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveCustomer(CustomerVM customerVm)
        {
            string msgSuccess = "";
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("AddCustomer", customerVm);
                }
                else
                {
                    var oCustomer = _mapper.Map<Customer>(customerVm);
                    
                    if(customerVm.Id == Guid.Empty)
                    {
                        _helperCustomer.Create(oCustomer);
                        msgSuccess = "El usuario se registró con éxito";
                    }
                    else
                    {
                        _helperCustomer.Update(oCustomer);
                        msgSuccess = "El usuario se actualizó con éxito";
                    }

                    ViewBag.messageSuccess = msgSuccess;
                }
            }
            catch (Exception ex)
            {
                ViewBag.MessageError = ex.Message;
                return View("AddCustomer", customerVm);
            }

            TempData["messageSuccess"] = msgSuccess;
            return RedirectToAction("Index");
        }
    }
}

TeCAS.SCA.WebAdmin/Controllers/TransactionController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using TeCAS.SCA.Entities;
using TeCAS.SCA.Services.Operations;
using TeCAS.SCA.WebAdmin.Models;

namespace TeCAS.SCA.WebAdmin.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ITransactionOperations _helperTransaction;
        private readonly IAccountOperations _helperAccount;
        private readonly IMapper _mapper;

        public TransactionController(ITransactionOperations helperTransaction, 
            IAccountOperations helperAccount, IMapper mapper)
        {
            _helperTransaction = helperTransaction;
            _helperAccount = helperAccount;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult DepositMoney()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DepositMoney(TransactionMoneyVM oTransactionVm)
        {
            string msgSuccess = "";
            try
            {
                _helperTransaction.DepositMoney(oTransactionVm.NoAccount, oTransactionVm.Amount);
                msgSuccess = "El depósito se registró con éxito";
            }
            catch (Exception ex)
            {
                ViewBag.MessageError = ex.Message;
                return View(oTransactionVm);
            }

            TempData["messageSuccess"] = msgSuccess;
            return RedirectToAction("Index");
        }

        public List<TransactionVM> GetTransactions()
        {
            var transactions = _helperTransaction.GetAllComplete();
            var transactionVm = _mapper.Map<List<Transaction>, List<TransactionVM>>(transactions);

            return transactionVm;
        }

        [HttpGet]
        public IActionResult HaveMoney()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult HaveMoney(TransactionMoneyVM oTransactionVm)
        {
            string msgSuccess = "";
            try
            {
                _helperTransaction.HaveMoney(oTransactionVm.NoAccount, oTransactionVm.Amount);
                msgSuccess = "El retiro se realizó con éxito";
            }
            catch (Exception ex)
            {
                ViewBag.MessageError = ex.Message;
                return View(oTransactionVm);
            }

            TempData["messageSuccess"] = msgSuccess;
            return RedirectToAction("Index");
        }
    }
}

TeCAS.SCA.WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TeCAS - Dashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link href="~/css/dataTables.min.css" rel="stylesheet" />
    <link href="~/css/app.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="p-0 navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TeCAS.SCA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link text-light dropdown-toggle" style="cursor:pointer;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="far fa-cash-register"></i> Cajero
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Transaction" 
                                   asp-action="DepositMoney">Depósitar dinero</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Transaction" 
                                   asp-action="HaveMoney">Retirar dinero</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Customer" asp-action="Index"><i class="fad fa-users-class"></i> Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Index"><i class="fas fa-file-invoice-dollar"></i> Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Transaction" asp-action="Index"><i class="far fa-money-bill-alt"></i> Reportes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TeCAS.SCA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>